[package]
name = "code_copy"
version = "0.1.2"
authors = ["Denis Kotlyarov (Денис Котляров) <denis2005991@gmail.com>"]
repository = "https://github.com/clucompany/CopyCode.git"
edition = "2021"

license = "Apache-2.0"
readme = "README.md"

[dependencies]
